$  % These are latex commands (i.e., macros). 
   \newcommand{\vec}[1]{ \boldsymbol{\mathbf{#1}} }
   \newcommand{\R}{\mathbb{R}}
   \newcommand{\C}{\mathbb{C}}
$

## THIS IS A TEST

We have latex new commands at the top of this cell -- namely __\vec__ and __\R__ and __\C__

If I execute this cell and then those below, everything works. 

BUT TWO ISSUES: 
1. When I load the notebook, the first few cells do not render using the __\newcommands__ defined at the top of this cell
2. I can't get __nbconvert__ to use the __newcommand__ definitions either 

In [1]:
import numpy as np ##  Now we do some Python

I have used a newcommand to redefine __\vec__ so that A vector now renders in bold (no "arrow over letter").   

Here is what this looks like in this cell: $\vec{v}$

I also have a __newcommand__ that defines __\R__ to be the math black-board bold double struck R: 

It renders as follows: $\R$ 

TO GET THIS CELL TO RENDER, I MUST PUT A SPACE OR MAKE OTHER MOD AND THEN EXECUTE.

In [2]:
A = np.random.rand(2,2)
A

array([[0.78185794, 0.95781878],
       [0.47493509, 0.29464465]])

Now more markdown: Here I just repeat the above: 

I have used a newcommand to redefine __\vec__ so that A vector now renders in bold (no "arrow over letter").  

Here is what this looks like in this cell: $\vec{v}$

I also have a __newcommand__ that defines __\R__ to be the math black-board bold double struck R:  

It renders as follows: $\R$  

In [3]:
A.trace()

np.float64(1.0765025904608754)

Again: I have used a newcommand to redefine __\vec__ so that A vector now renders in bold (no "arrow over letter").  

Here is what this looks like in this cell: $\vec{v}$

I also have a __newcommand__ that defines __\R__ to be the math black-board bold double struck R:  

It renders as follows: $\R$  

In [4]:
A @ A.T

array([[1.52871865, 0.65354795],
       [0.65354795, 0.31237881]])

Again: I have used a newcommand to redefine __\vec__ so that A vector now renders in bold (no "arrow over letter").  

Here is what this looks like in this cell: $\vec{v}$

I also have a __newcommand__ that defines __\R__ to be the math black-board bold double struck R:  

It renders as follows: $\R$  

In [5]:
np.linalg.det(A)

np.float64(-0.22453148697258585)

Again: I have used a newcommand to redefine __\vec__ so that A vector now renders in bold (no "arrow over letter").  

Here is what this looks like in this cell: $\vec{v}$

I also have a __newcommand__ that defines __\R__ to be the math black-board bold double struck R:   

It renders as follows: $\R$  

In [6]:
np.linalg.norm(A)

np.float64(1.3568704659129924)

Again: I have used a newcommand to redefine __\vec__ so that A vector now renders in bold (no "arrow over letter").  

Here is what this looks like in this cell: $\vec{v}$

I also have a __newcommand__ that defines __\R__ to be the math black-board bold double struck R:    

It renders as follows: $\R$  

In [7]:
np.linalg.norm(A,1)

np.float64(1.2567930252679376)

Again: I have used a newcommand to redefine __\vec__ so that A vector now renders in bold (no "arrow over letter").  

Here is what this looks like in this cell: $\vec{v}$

I also have a __newcommand__ that defines __\R__ to be the math black-board bold double struck R:    

It renders as follows: $\R$  

In [8]:
np.linalg.norm(A,'fro')

np.float64(1.3568704659129924)

Again: I have used a newcommand to redefine __\vec__ so that A vector now renders in bold (no "arrow over letter").  

Here is what this looks like in this cell: $\vec{v}$

I also have a __newcommand__ that defines __\R__ to be the math black-board bold double struck R:    

It renders as follows: $\R$  

In [9]:
np.linalg.norm(A.T @ A, 2)

np.float64(1.8132948181795174)

Again: I have used a newcommand to redefine __\vec__ so that A vector now renders in bold (no "arrow over letter").  

Here is what this looks like in this cell: $\vec{v}$

I also have a __newcommand__ that defines __\R__ to be the math black-board bold double struck R:    

It renders as follows: $\R$ 

In [10]:
np.sum(A)

np.float64(2.509256460951664)

Again: I have used a newcommand to redefine __\vec__ so that A vector now renders in bold (no "arrow over letter").  

Here is what this looks like in this cell: $\vec{v}$

I also have a __newcommand__ that defines __\R__ to be the math black-board bold double struck R:    

It renders as follows: $\R$ 

In [11]:
A.copy() @ A

array([[1.06620358, 1.0310944 ],
       [0.51126885, 0.54171722]])

Again: I have used a newcommand to redefine __\vec__ so that A vector now renders in bold (no "arrow over letter").  

Here is what this looks like in this cell: $\vec{v}$

I also have a __newcommand__ that defines __\R__ to be the math black-board bold double struck R:    

It renders as follows: $\R$ 

In [12]:
np.triu(A.copy())

array([[0.78185794, 0.95781878],
       [0.        , 0.29464465]])

Again: I have used a newcommand to redefine __\vec__ so that A vector now renders in bold (no "arrow over letter").  

Here is what this looks like in this cell: $\vec{v}$

I also have a __newcommand__ that defines __\R__ to be the math black-board bold double struck R:   

It renders as follows: $\R$

I also have a __newcommand__ that defines __\C__ to be the math black-board bold double struck C:   

It renders as follows: $\C$ 